---
- name: "Installing ElasticSearch(2.4) Server"
  homebrew: 
    name: elasticsearch@2.4 
    state: present
  tags:
    - always

- name: setup elasticsearch plugins
  shell: "{{ brew_install_path }}/opt/elasticsearch@2.4/libexec/bin/plugin install {{ item }}"
  with_items:
    - "delete-by-query"
  tags:
    - always
