---
- name: "Ensure redisdb"
  homebrew: 
    name: redis
    state: present
  tags:
    - always

- name: "Create {{ homebrew_install_path }}/etc/supervisor.d/redisdb.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ homebrew_install_path }}/etc/supervisor.d/redisdb.ini"
  when: not state.stat.exists
  tags:
    - always
