---
- name: "Creates directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ www_dir }}"
    - "{{ brew_install_path }}/etc/nginx/servers_custom"
  ignore_errors: yes
  tags:
    - always

- name: "Installing Nginx"
  homebrew:
    name: nginx
    state: present
  tags:
    - always

- name: "Creates {{ brew_install_path }}/etc/nginx/nginx.conf"
  template:
    src: nginx.conf.j2
    dest: "{{ brew_install_path }}/etc/nginx/nginx.conf"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
  tags:
    - always

- name: "Creates {{ brew_install_path }}/etc/nginx/conf.d"
  file:
    path: "{{ brew_install_path }}/etc/nginx/conf.d"
    state: directory
    mode: 0755
  tags:
    - always

- stat: 
    path: "{{ brew_install_path }}/etc/supervisor.d/nginx.ini"
  register: state
  tags:
    - always

- name: "Create etc/supervisor.d/nginx.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/nginx.ini"
  when: not state.stat.exists
  tags:
    - always

- name: Create a log directories
  file:
    path: '{{ brew_install_path }}/var/log/nginx'
    state: directory
    owner: '{{ brew_user }}'
    group: '{{ brew_group }}'
    mode: '0775'
    recurse: true
  become: yes
  tags:
    - always

- name: "Creates {{ brew_install_path }}/etc/logrotate.d/nginx.conf"
  template:
    src: logrotate.nginx.conf.j2
    dest: "{{ brew_install_path }}/etc/logrotate.d/nginx.conf"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
  tags:
    - always

- name: Include firewall_{{ ansible_system | lower }}.yml
  include: "firewall_{{ ansible_system | lower }}.yml"