---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"

- name: "Unlink all already installed php packages"
  shell: "brew list | grep php | xargs brew unlink"

- name: "Remove previously installed php71 packages"
  shell: "brew list | grep ^php71 | xargs brew uninstall --ignore-dependencies --force"
  ignore_errors: yes
  tags:
    - reinstall

- name: "Installing php71 with flags: {{ php71_flags }}"
  homebrew:
    name: php71 
    state: present 
    install_options: "{{ php71_flags }}"
  async: 1800
  poll: 15

- name: "Installing php71 modules"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ php71_modules }}"

- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/7.1/php-fpm.conf owner={{ www_user }} group={{ www_group }}

- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.1/php.ini owner={{ www_user }} group={{ www_group }}

- name: "Create ext-opcache.ini"
  template: src=ext-opcache.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.1/conf.d/ext-opcache.ini owner={{ www_user }} group={{ www_group }}

- name: "Create ext-xdebug.ini"
  template: src=ext-xdebug.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.1/conf.d/ext-xdebug.ini owner={{ www_user }} group={{ www_group }}

- name: "Unlink php71"
  homebrew: "name=php71 state=unlinked"
  ignore_errors: yes

- name: "Add simlink"
  shell: "find /usr/local/Cellar/php71 -path '*/bin/php' | awk -F/ '{print \"ln -Fs \" $0 \" \" \"/usr/local/bin/\"$5}' | bash"
  ignore_errors: yes

- name: add 71 to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ '71' ] }} "
