---
- name: "Installing golang"
  homebrew: 
    name: go 
    state: present
    install_options: "cross-compile-common"
  tags:
    - always
    
- name: "Adding GOPATH to env"
  blockinfile:
    dest: '{{ ansible_env.HOME }}/{{item}}'
    marker: "# {mark} golang"
    block: |
      export GOPATH="${HOME}/go"
      export PATH="${PATH}:${GOPATH}/bin"
  with_items: ['.zshrc', '.bashrc']
