---
- name: Ensure required taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "sergeycherepanov/php"

- name: "Ensure zlib"
  homebrew:
    name: zlib
    state: present

- name: "Resolve zlib path"
  shell: "brew --prefix zlib"
  register: result

- name: "Register zlib_path fact"
  set_fact: zlib_path="{{ result.stdout }}"

- name: "Installing Curl with openssl"
  homebrew: 
    name: sergeycherepanov/php/curl
    state: present
    install_options: with-openssl,with-libssh2
  environment:
    ZLIB_PATH: "{{ zlib_path }}"
