---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "kyslik/homebrew-php"
  tags:
    - php72

- name: "Unlink all already installed php packages"
  shell: "brew list | grep php | xargs brew unlink"
  tags:
    - php72

- name: "Installing php72 with flags: {{ php72_flags }}"
  homebrew:
    name: php72 
    state: latest 
    install_options: "{{ php72_flags }}"
  tags:
    - php72

- name: "Installing php72 modules"
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php72_modules }}"
  tags:
    - php72

- name: "Remove outdated php72"
  shell: "brew upgrade --cleanup php72"
  ignore_errors: yes
  tags:
    - php71

- name: "Installing php72 pear packages modules"
  shell: "pear install {{ item }}"
  with_items: "{{ php72_pear_packages }}"
  tags:
    - php72

- name: "Create php-fpm.conf"
  template:
    src: php-fpm.conf.j2
    dest: "{{ homebrew_install_path }}/etc/php/7.2/php-fpm.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - php72

- name: "Create php.ini"
  template:
    src: php.ini.j2
    dest: "{{ homebrew_install_path }}/etc/php/7.2/php.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - php72

#- stat: 
#    path: "{{ homebrew_install_path }}/etc/php/7.2/php-fpm-xdebug.conf"
#  register: state

- name: "Create php-fpm-xdebug.conf"
  template: 
      src: php-fpm-xdebug.conf.j2
      dest: "{{ homebrew_install_path }}/etc/php/7.2/php-fpm-xdebug.conf"
      owner: "{{ www_user }}"
      group: "{{ www_group }}"
#  when: not state.stat.exists
  tags:
    - php72

#- stat: 
#    path: "{{ homebrew_install_path }}/etc/php/7.2/php-xdebug.ini"
#  register: state

- git:
    repo: 'https://github.com/tideways/php-profiler-extension.git'
    dest: "/tmp/xhprof{{php_version}}"
    version: 'master'
  tags:
    - php72

- name: "Install xhprof extension"
  shell: >
    {{ homebrew_install_path }}/opt/{{php_version}}/bin/phpize &&
    ./configure --with-php-config={{ homebrew_install_path }}/opt/{{php_version}}/bin/php-config &&
    make &&
    make install
  args:
    chdir: "/tmp/xhprof{{php_version}}"
  tags:
    - php72

- name: "Ensure ext-xhprof.ini"
  copy:
    content: "extension=tideways_xhprof.so"
    dest: "{{ homebrew_install_path }}/etc/php/{{ php_version_num }}/conf.d/ext-xhprof.ini"
  tags:
    - php72

- name: "Create php-xdebug.ini"
  template: 
      src: php-xdebug.ini.j2
      dest: "{{ homebrew_install_path }}/etc/php/7.2/php-xdebug.ini"
      owner: "{{ www_user }}"
      group: "{{ www_group }}"
#  when: not state.stat.exists
  tags:
    - php72

#- stat: 
#    path: "{{ homebrew_install_path }}/etc/php/7.2/conf.d/ext-opcache.ini"
#  register: state

- name: "Create ext-opcache.ini"
  template: 
    src: "ext-opcache.ini.j2"
    dest: "{{ homebrew_install_path }}/etc/php/7.2/conf.d/ext-opcache.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
#  when: not state.stat.exists
  tags:
    - php72

- name: "Unlink php72"
  homebrew: "name=php72 state=unlinked"
  ignore_errors: yes
  tags:
    - php72

- name: "Add wrapper"
  template:
    src: "php.j2"
    dest: "{{ homebrew_install_path }}/bin/{{ php_version_legacy }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0755
  tags:
    - php72

- name: add 72 to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ '72' ] }} "
  tags:
    - php72

#- stat: 
#    path: "{{ homebrew_install_path }}/etc/supervisor.d/php72.ini"
#  tags:
#    - php72
#  register: state

- name: "Create etc/supervisor.d/php72.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ homebrew_install_path }}/etc/supervisor.d/php72.ini"
#  when: not state.stat.exists
  tags:
    - php72
