---

- name: "Ensure EFK directory"
  file:
    path: "{{ brew_install_path }}/etc/efk/td-agent/conf.d"
    state: directory

- name: "Creates {{ brew_install_path }}/etc/efk/td-agent/conf.d/nginx.conf"
  template:
    src: td-agent.nginx.conf.j2
    dest: "{{ brew_install_path }}/etc/efk/td-agent/conf.d/nginx.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
