---
php_version: php74
php_version_num: 7.4
php_version_num_int: 74
php_flags: ""
php_dependencies:
php_modules:
    - intl
    - mcrypt
    - xdebug
    - redis
    - tidy
    - opcache
    - pdo-pgsql
    - xhprof
    - mongodb
    - apcu
    - memprof
    - imagick
php_pear_packages: []
