---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"

- name: "Installing php56 with fpm"
  homebrew: "name=php56 state=present install_options=with-fpm,with-mysql,without-apache,with-homebrew-curl"
  async: 1800
  poll: 15

- name: "Installing php56-mcrypt"
  homebrew: "name=php56-mcrypt state=present"

- name: "Installing php56-intl"
  homebrew: "name=php56-intl state=present"

- name: "Installing php56-xdebug"
  homebrew: "name=php56-xdebug state=present"

- name: "Installing php56-redis"
  homebrew: "name=php56-redis state=present"

- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/5.6/php-fpm.conf owner={{ www_user }} group={{ www_group }}

- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.6/php.ini owner={{ www_user }} group={{ www_group }}

- name: "Create ext-xdebug.ini"
  template: src=ext-xdebug.ini.j2 dest={{ homebrew_install_path }}/etc/php/5.6/conf.d/ext-xdebug.ini owner={{ www_user }} group={{ www_group }}

- name: "Unlink php56"
  homebrew: "name=php56 state=unlinked"
  ignore_errors: yes

- name: "Add simlink"
  shell: "find /usr/local/Cellar/php56 -path '*/bin/php' | awk -F/ '{print \"ln -Fs \" $0 \" \" \"/usr/local/bin/\"$5}' | bash"

- name: add 56 to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ '56' ] }} "
