---
- name: "Installing phps with flags: {{ php_flags }}"
  homebrew:
    name: php56
    state: present
    install_options: "{{ php_flags }}"
  with_items: "{{ php_versions }}"
  tags:
    - php56

- name: "Installing {{ php_version }} modules"
  homebrew:
    name: "{{php_version}}-{{ item }}"
    state: present
    install_options: "build-from-source"
  with_items: "{{ php_modules }}"
  tags:
    - php56

- name: "Remove outdated {{ php_version }}"
  shell: "brew upgrade --cleanup {{ php_version }}"
  ignore_errors: yes
  tags:
    - php56

- name: "Installing {{ php_version }} pear packages modules"
  shell: "pear install {{ item }}"
  with_items: "{{ php_pear_packages }}"
  tags:
    - php56

- name: "Add wrapper"
  template:
    src: "php.j2"
    dest: "{{ brew_install_path }}/bin/{{ php_version }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0755
  tags:
    - php56

- name: "Ensure xphp wrapper directory"
  file:
    path: "{{ brew_install_path }}/opt/xphp/{{ php_version_num }}/bin"
    state: directory
  tags:
    - php56

- name: "Ensure xphp bin"
  template:
    src: "xphp-bin.j2"
    dest: "{{ brew_install_path }}/opt/xphp/{{ php_version_num }}/bin/php"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0755
  tags:
    - php56

- name: "Add xphp wrapper"
  template:
    src: "xphp.j2"
    dest: "{{ brew_install_path }}/bin/x{{ php_version }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0755
  tags:
    - php56

- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ brew_install_path }}/etc/php/5.6/php-fpm.conf owner={{ www_user }} group={{ www_group }}
  #  when: not state.stat.exists
  tags:
    - php56


- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ brew_install_path }}/etc/php/5.6/php.ini owner={{ www_user }} group={{ www_group }}
  #  when: not state.stat.exists
  tags:
    - php56


- name: "Create php-fpm-xdebug.conf"
  template:
    src: php-fpm-xdebug.conf.j2
    dest: "{{ brew_install_path }}/etc/php/5.6/php-fpm-xdebug.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  #  when: not state.stat.exists
  tags:
    - php56


- name: "Disabling xdebug extension by default"
  lineinfile:
    path: '{{ brew_install_path }}/etc/php/{{ php_version_num }}/conf.d/ext-xdebug.ini'
    regexp: '^(zend_extension=.*)'
    line: ';\1'
    backrefs: yes
  tags:
    - php56


- name: "Create php-xdebug.ini"
  template:
    src: php.ini.j2
    dest: "{{ brew_install_path }}/etc/php/{{ php_version_num }}/php-xdebug.ini"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  #  when: not state.stat.exists
  tags:
    - php56

- blockinfile:
    dest: '{{ brew_install_path }}/etc/php/{{ php_version_num }}/php-xdebug.ini'
    marker: "; {mark} ansible xdebug"
    block: |
      [xdebug]
      zend_extension="{{ brew_install_path }}/opt/{{ php_version }}-xdebug/xdebug.so"
      xdebug.remote_enable=1
      xdebug.remote_autostart = 0
      xdebug.remote_connect_back = 0
      xdebug.remote_host=127.0.0.1
      xdebug.remote_port=92{{ php_version_num_int }}
      xdebug.profiler_enable=0
      xdebug.profiler_output_dir=/tmp/xdebug{{ php_version_num_int }}
      xdebug.idekey=PHPSTORM
      xdebug.overload_var_dump=0
      xdebug.max_nesting_level=500
  tags:
    - php56


- name: Resolve extension dir
  shell: "{{ brew_install_path }}/bin/php{{ php_version_num_int }} -i | grep -e '^extension_dir' | awk -F'=>' '{print $2}'"
  register: output
  tags:
    - php56

- name: Register php_extension_dir
  set_fact:
    php_extension_dir: "{{ output.stdout | trim }}"
  tags:
    - php56

- name: "Create ext-opcache.ini"
  template: src=ext-opcache.ini.j2 dest={{ brew_install_path }}/etc/php/5.6/conf.d/ext-opcache.ini owner={{ www_user }} group={{ www_group }}
  #  when: not state.stat.exists
  tags:
    - php56

- name: "Unlink {{ php_version }}"
  homebrew:
    name: "{{ php_version }}"
    state: "unlinked"
  ignore_errors: yes
  tags:
    - php56


- name: Setting default php to {{ php_version_num_int }}
  set_fact:
    default_php: "{{ php_version_num_int }}"
  tags:
    - php56

- debug:
    var: php_versions
  tags:
    - php56


- name: "Create etc/supervisor.d/{{ php_version }}.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/{{ php_version }}.ini"
  #  when: not state.stat.exists
  tags:
    - php56

- name: "Ensure EFK config directory"
  file:
    path: "{{ brew_install_path }}/etc/efk/td-agent/conf.d"
    state: directory
  tags:
    - php56

- name: "Creates {{ brew_install_path }}/etc/efk/td-agent/conf.d/php{{ php_version_num }}.conf"
  template:
    src: td-agent.php.conf.j2
    dest: "{{ brew_install_path }}/etc/efk/td-agent/conf.d/php{{ php_version_num }}.conf"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
  tags:
    - php56

- name: "Linking php"
  shell: "brew link {{ php_version }}"
  tags:
    - php56