---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"

- name: "Installing php70 with fpm"
  homebrew: "name=php70 state=present install_options=with-fpm,with-mysql,without-apache,disable-opcache,with-homebrew-curl"

- name: "Installing php70-mcrypt"
  homebrew: "name=php70-mcrypt state=present"

- name: "Installing php70-intl"
  homebrew: "name=php70-intl state=present install_options=build-from-source"

- name: "Installing php70-xdebug"
  homebrew: "name=php70-xdebug state=present"

- name: "Installing php70-redis"
  homebrew: "name=php70-redis state=present"

- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/7.0/php-fpm.conf owner={{ www_user }} group={{ www_group }}

- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.0/php.ini owner={{ www_user }} group={{ www_group }}

- name: "Create ext-xdebug.ini"
  template: src=ext-xdebug.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.0/conf.d/ext-xdebug.ini owner={{ www_user }} group={{ www_group }}

- name: "Unlink php70"
  homebrew: "name=php70 state=unlinked"
  ignore_errors: yes

- name: "Add simlink"
  shell: "find /usr/local/Cellar/php70 -path '*/bin/php' | awk -F/ '{print \"ln -Fs \" $0 \" \" \"/usr/local/bin/\"$5}' | bash"

- name: add 70 to "php_versions" array
  set_fact: 
    php_versions: "{{ php_versions + [ '70' ] }} "
