---
mysql_version: "5.6"
mysql_version_num: "56"
mysql_formula: "percona-server@5.6"
#mysql_base_dir: "{{ homebrew_install_path }}/opt/percona-server@5.6"
mysql_etc_dir: "{{ homebrew_install_path }}/etc/mysql/56"
mysql_run_dir: "{{ homebrew_install_path }}/var/run/mysql/56"
mysql_log_dir: "{{ homebrew_install_path }}/var/log/mysql/56"
mysql_data_dir: "{{ homebrew_install_path }}/var/lib/mysql/56"
mysql_tmp_dir: /tmp
mysql_listen_port: 3306
mysql_listen_address: 127.0.0.1
mysql_supervisord_name: mysql56
