---
mysql_tap: "digitalspacestdio/common"
mysql_user: "{{ brew_user }}"
mysql_group: "{{ brew_group }}"
mysql_version: "5.6"
mysql_version_num: "56"
mysql_formula: "digitalspacestdio/common/percona-server@5.6"
#mysql_base_dir: "{{ brew_install_path }}/opt/percona-server@5.6"
mysql_etc_dir: "{{ brew_install_path }}/etc/mysql/56"
mysql_run_dir: "{{ brew_install_path }}/var/run/mysql/56"
mysql_log_dir: "{{ brew_install_path }}/var/log/mysql/56"
mysql_data_dir: "{{ brew_install_path }}/var/lib/mysql/56"
mysql_tmp_dir: /tmp
mysql_listen_port: 3356
mysql_listen_address: 127.0.0.1
mysql_supervisord_name: mysql56
mysql_root_password: root
