---
- name: "Configure global .gitignore"
  template: 
    src: .gitignore.j2
    dest: "{{ brew_user_home_dir }}/.gitignore"
  tags:
    - always

- name: git config
  shell: "git config --global core.excludesfile {{ brew_user_home_dir }}/.gitignore"
  tags:
    - always
