---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - "homebrew/dupes"
    - "homebrew/php"
- name: "Installing php70 with fpm"
  homebrew: "name=php70 state=present install_options=with-fpm,with-mysql,without-apache,disable-opcache"
- name: "Unlink php70"
  homebrew: "name=php70 state=linked"
- name: "Installing php70-mcrypt"
  homebrew: "name=php70-mcrypt state=present"
- name: "Installing php70-intl"
  homebrew: "name=php70-intl state=present"
- name: "Installing php70-xdebug"
  homebrew: "name=php70-xdebug state=present"
- name: "Installing php70-redis"
  homebrew: "name=php70-redis state=head"
- name: "Create php-fpm.conf"
  template: src=php-fpm.conf.j2 dest={{ homebrew_install_path }}/etc/php/7.0/php-fpm.conf owner={{ www_user }} group={{ www_group }}
- name: "Create php.ini"
  template: src=php.ini.j2 dest={{ homebrew_install_path }}/etc/php/7.0/php.ini owner={{ www_user }} group={{ www_group }}
- name: "Unlink php70"
  homebrew: "name=php70 state=unlinked"
- name: "Creates {{ www_dir }}/dev70/info directory"
  file: path={{ www_dir }}/dev70/info state=directory
- name: "Create info.dev70 host"
  template: src=index.php dest={{ www_dir }}/dev70/info/index.php owner={{ www_user }} group={{ www_group }}
