---
- name: "Installing dnsmasq"
  apt:
    name: dnsmasq
    state: present
  become: yes
  tags:
  - always

- stat:
    path: "/etc/NetworkManager/dnsmasq.d"
  register: state_networkmanager_dnsmaq_dir
  become: yes
  tags:
  - always

- stat:
    path: "/etc/dnsmasq.d"
  register: state_dnsmaq_dir
  when: not state_networkmanager_dnsmaq_dir.stat.exists
  become: yes
  tags:
  - always

- name: Register mysql_base_dir fact
  set_fact:
    dnsmasq_conf_dirs: "{{ dnsmasq_conf_dirs + [ state_dnsmaq_dir.stat.path ] }}"
  when: state_dnsmaq_dir is defined and state_dnsmaq_dir.stat.exists
  tags:
  - always

- name: Register mysql_base_dir fact
  set_fact:
    dnsmasq_conf_dirs: "{{ dnsmasq_conf_dirs + [ state_networkmanager_dnsmaq_dir.stat.path ] }}"
  when: state_networkmanager_dnsmaq_dir.stat.exists
  tags:
  - always

- name: "Bind dnsmasq to 127.0.0.1"
  lineinfile:
    path: '/etc/dnsmasq.conf'
    line: 'listen-address=127.0.0.1'
  when: state_dnsmaq_dir is defined and state_dnsmaq_dir.stat.exists
  become: yes
  tags:
  - always

- name: "Configure *.dev.com zone resolver"
  copy:
    content: "address=/.dev.com/127.0.0.1"
    dest: "{{ item }}/dev.com.conf"
  with_items: "{{ dnsmasq_conf_dirs }}"
  become: yes
  tags:
  - always

- name: "Configure *.loc.com zone resolver"
  copy:
    content: "address=/.dev.loc/127.0.0.1"
    dest: "{{ item }}/dev.loc.conf"
  with_items: "{{ dnsmasq_conf_dirs }}"
  become: yes
  tags:
  - always

- file:
    state: absent
    path: "{{ brew_install_path }}/etc/supervisor.d/dnsmasq.ini"
  tags:
  - always

- ini_file:
    path: "/etc/NetworkManager/NetworkManager.conf"
    section: "main"
    option: "dns"
    value: "dnsmasq"
  when: state_networkmanager_dnsmaq_dir.stat.exists
  tags:
  - always

- ini_file:
    path: "/etc/systemd/resolved.conf"
    section: "Resolve"
    option: "DNSStubListener"
    value: "no"
  when: state_dnsmaq_dir is defined and state_dnsmaq_dir.stat.exists
  tags:
  - always

- name: "Restarting network-manager"
  systemd:
    name: network-manager
    state: restarted
  become: yes
  when: state_networkmanager_dnsmaq_dir.stat.exists
  tags:
  - always

- name: "Disabling systemd-resolved"
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  become: yes
  when: state_dnsmaq_dir is defined and state_dnsmaq_dir.stat.exists
  ignore_errors: yes
  tags:
  - always

- name: "Restarting dnsmasq"
  systemd:
    name: dnsmasq
    state: restarted
  become: yes
  when: state_dnsmaq_dir is defined and state_dnsmaq_dir.stat.exists
  tags:
  - always
