---
- name: "Installing DNSMASQ"
  homebrew:
    name: dnsmasq
    state: latest

#- name: "Truncate configuration file"
#  shell: "echo '' > {{ brew_install_path }}/etc/dnsmasq.conf"
#  tags:
#    - always

- name: "Creates /etc/resolver directory"
  file:
    path: /etc/resolver
    state: directory
  become: yes
  become_method: sudo

- name: "Change fnsmasq port to 5353"
  lineinfile:
    path: '{{ brew_install_path }}/etc/dnsmasq.conf'
    regexp: '.*port=.*'
    line: 'port=5353'

- name: "Adding *.dev.com zone to dnsmasq configuration file"
  lineinfile:
    path: '{{ brew_install_path }}/etc/dnsmasq.conf'
    line: 'address=/dev.com/127.0.0.1'

- name: "Adding *.loc.com zone to dnsmasq configuration file"
  lineinfile:
    path: '{{ brew_install_path }}/etc/dnsmasq.conf'
    line: 'address=/loc.com/127.0.0.1'

- name: "Configure *.dev.com zone resolver"
  copy:
    content: "nameserver 127.0.0.1"
    dest: "/etc/resolver/dev.com"
  become: yes

- name: "Configure *.loc.com zone resolver"
  copy:
    content: "nameserver 127.0.0.1"
    dest: "/etc/resolver/loc.com"
  become: yes

- stat:
    path: "{{ brew_install_path }}/etc/supervisor.d/dnsmasq.ini"
  register: state

- name: "Create etc/supervisor.d/dnsmasq.ini"
  template:
    src: supervisord.ini.j2
    dest: "{{ brew_install_path }}/etc/supervisor.d/dnsmasq.ini"
  when: not state.stat.exists
