---
homebrew_install_path: /usr/local
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  - ssh-copy-id
  - pv
  - htop
  - mc
  - wget
  - mtr

homebrew_upgrade_all_packages: no

homebrew_taps:
  - caskroom/cask

homebrew_cask_apps:
  - launchrocket
#  - sequel-pro
  - iterm2
#  - atom
#  - google-chrome
#  - skype
#  - phpstorm
#  - teamviewer
#  - dropbox
  - virtualbox
  - vagrant

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
