---
brew_brew_bin_path: "{{ brew_install_path }}/bin"

brew_installed_packages:
  - ssh-copy-id
  - pv
  - htop
  - mc
  - wget
  - mtr
  - nmap
  - watch
  - hg
  - bzr
  - p7zip
  - autoconf
  - gomplate
  - gettext
  - glances
  - json-table
  - pup
  - fswatch
  - shellcheck
  - libmcrypt
  - yarn

brew_upgrade_all_packages: no

brew_taps:
  - homebrew/cask
  - djocker/common
  - homebrew/cask-fonts 

brew_cask_apps:
  - font-hack-nerd-font

brew_cask_appdir: /Applications

brew_use_brewfile: true
brew_brewfile_dir: '~'
brew_directories:
  - '{{ brew_install_path }}/bin'
  - '{{ brew_install_path }}/etc'
  - '{{ brew_install_path }}/include'
  - '{{ brew_install_path }}/lib'
  - '{{ brew_install_path }}/sbin'
  - '{{ brew_install_path }}/share'
  - '{{ brew_install_path }}/opt'
  - '{{ brew_install_path }}/var'
  - '{{ brew_install_path }}/Cellar'
  - '{{ brew_install_path }}/Caskroom'
  - '{{ brew_install_path }}/Homebrew'
  - '{{ brew_install_path }}/Frameworks'
  - '{{ brew_install_path }}/etc/bash_completion.d'
  - '{{ brew_install_path }}/lib/pkgconfig'
  - '{{ brew_install_path }}/share/aclocal'
  - '{{ brew_install_path }}/share/doc'
  - '{{ brew_install_path }}/share/info'
  - '{{ brew_install_path }}/share/locale'
  - '{{ brew_install_path }}/share/man'
  - '{{ brew_install_path }}/share/man/man1'
  - '{{ brew_install_path }}/share/man/man2'
  - '{{ brew_install_path }}/share/man/man3'
  - '{{ brew_install_path }}/share/man/man4'
  - '{{ brew_install_path }}/share/man/man5'
  - '{{ brew_install_path }}/share/man/man6'
  - '{{ brew_install_path }}/share/man/man7'
  - '{{ brew_install_path }}/share/man/man8'
  - '{{ brew_install_path }}/var/log'
  - '{{ brew_install_path }}/var/homebrew'
  - '{{ brew_install_path }}/var/homebrew/linked'
  - '{{ brew_install_path }}/bin/brew'
  - '{{ brew_install_path }}/share/zsh'
  - '{{ brew_install_path }}/share/zsh/site-functions'
